version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - frontend-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge